{
    "population_size": 1_000,
    "total_steps": 300,
    "initial_infected_count": 20,
    "latent_to_silent_days": dist(1, 3),
    "silent_to_asymptomatic_days": dist(0, 3, 10),
    "silent_to_symptomatic_days": dist(0, 3, 10),
    "asymptomatic_to_recovered_days": dist(3, 5, 7),
    "symptomatic_to_asymptomatic_days": dist(7, 10, 14),
    "symptomatic_to_hospitalized_days": dist(0, 1.5, 10),
    "hospitalized_to_asymptomatic_days": dist(18),
    "hospitalized_to_icu_days": dist(5),
    "icu_to_deceased_days": dist(7),
    "icu_to_hospitalized_days": dist(7),
    "silent_to_asymptomatic_probability": 0.2,
    "symptomatic_to_asymptomatic_probability": 0.85,
    "hospitalized_to_asymptomatic_probability": 0.8,
    "icu_to_hospitalized_probability": 0.65,
    "symptomatic_infection_ratio": 0.75,
    "asymptomatic_infection_ratio": 0.25,
    "silent_infection_ratio": 0.3,
    "r0": 2.4,
    "home_isolation_sicks": False,
    "full_isolation_sicks": False,
    "caught_sicks_ratio": 0.3,
    "active_isolation": False,
    "stop_work_days": 40,
    "resume_work_days": 80,
    "family_size_distribution": rv_discrete(
        1, 7, name="family", values=([1, 2, 3, 4, 5, 6, 7], [0.095, 0.227, 0.167, 0.184, 0.165, 0.081, 0.081])
    ),
    "work_size_distribution": dist(30, 80),
    "work_scale_factor": 40,
    "average_amount_of_strangers": 200,
    "strangers_scale_factor": 150,
    "school_scale_factor": 100,
    "family_strength_not_workers": 0.75,
    "family_strength": 1,
    "work_strength": 0.1,
    "stranger_strength": 0.01,
    "school_strength": 0.1,
    "detection_rate": 0.7,
}
